"""AGRA Phase 2 — Agent-local database models package."""

from .drawing_models import (
    DrawingType,
    DrawingFeature,
    MeasurementUnit,
    Dimension,
    ToleranceSpec,
    TitleBlock,
    EquipmentTag,
    ComplianceNote,
    StageConfidence,
    AnalysisConfidence,
    DrawingAnalysisResult,
    DrawingAnalysisRequest,
    DrawingAnalysisResponse,
    ChatDrawingAnalysis,
    LegacyDrawingResult,
)

# Compliance Module Phase 1
from .compliance_models import (
    ComplianceStatus,
    ClauseStatus,
    Recommendation,
    ClauseCategory,
    ComplianceEvaluationRequest,
    ClauseScoreRequest,
    ComplianceReportRequest,
    ComplianceClauseBase,
    ComplianceClauseResponse,
    ClauseScoreBase,
    ClauseScoreResponse,
    ComplianceSummary,
    ComplianceEvaluationResponse,
    ComplianceListResponse,
    ComplianceReportResponse,
    SmartComplianceSuggestion,
    ComplianceProgressUpdate,
    SimpleComplianceResult,
)

__all__ = [
    # Drawing Models
    "DrawingType",
    "DrawingFeature",
    "MeasurementUnit",
    "Dimension",
    "ToleranceSpec",
    "TitleBlock",
    "EquipmentTag",
    "ComplianceNote",
    "StageConfidence",
    "AnalysisConfidence",
    "DrawingAnalysisResult",
    "DrawingAnalysisRequest",
    "DrawingAnalysisResponse",
    "ChatDrawingAnalysis",
    "LegacyDrawingResult",
    # Compliance Models
    "ComplianceStatus",
    "ClauseStatus",
    "Recommendation",
    "ClauseCategory",
    "ComplianceEvaluationRequest",
    "ClauseScoreRequest",
    "ComplianceReportRequest",
    "ComplianceClauseBase",
    "ComplianceClauseResponse",
    "ClauseScoreBase",
    "ClauseScoreResponse",
    "ComplianceSummary",
    "ComplianceEvaluationResponse",
    "ComplianceListResponse",
    "ComplianceReportResponse",
    "SmartComplianceSuggestion",
    "ComplianceProgressUpdate",
    "SimpleComplianceResult",
]
