"""AGRA Phase 2 — Agent-local database models package."""

from .drawing_models import (
    DrawingType,
    DrawingFeature,
    MeasurementUnit,
    Dimension,
    ToleranceSpec,
    TitleBlock,
    EquipmentTag,
    ComplianceNote,
    StageConfidence,
    AnalysisConfidence,
    DrawingAnalysisResult,
    DrawingAnalysisRequest,
    DrawingAnalysisResponse,
    ChatDrawingAnalysis,
    LegacyDrawingResult,
)

# Compliance Module Phase 2 — Rebuild Models
from .compliance_models import (
    VerdictEnum,
    SeverityEnum,
    RecommendationEnum,
    Citation,
    HouseRuleFlag,
    Contradiction,
    HistoricalNote,
    ClauseResultData,
    RunStatusEnum,
    ProgressUpdate,
    IngestBundleRequest,
    IngestBundleResponse,
    RunPipelineRequest,
    PipelineResult,
    StandardsDocument,
)

__all__ = [
    # Drawing Models
    "DrawingType",
    "DrawingFeature",
    "MeasurementUnit",
    "Dimension",
    "ToleranceSpec",
    "TitleBlock",
    "EquipmentTag",
    "ComplianceNote",
    "StageConfidence",
    "AnalysisConfidence",
    "DrawingAnalysisResult",
    "DrawingAnalysisRequest",
    "DrawingAnalysisResponse",
    "ChatDrawingAnalysis",
    "LegacyDrawingResult",
    # Compliance Models (Phase 2)
    "VerdictEnum",
    "SeverityEnum",
    "RecommendationEnum",
    "Citation",
    "HouseRuleFlag",
    "Contradiction",
    "HistoricalNote",
    "ClauseResultData",
    "RunStatusEnum",
    "ProgressUpdate",
    "IngestBundleRequest",
    "IngestBundleResponse",
    "RunPipelineRequest",
    "PipelineResult",
    "StandardsDocument",
]
